### ISSUE TITLE
Python 3.11 TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by elhakimz** [leon-thomm/Ryven#147]
always like this when try creating a new project
runs using python 3.11
Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

Traceback (most recent call last):
  File "/usr/local/bin/ryven", line 8, in <module>
    sys.exit(run_ryven())
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ryven/main/Ryven.py", line 75, in run
    editor = MainWindow(editor_init_config, window_title, window_theme, flow_theme, parent=gui_parent)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ryven/gui/main_window.py", line 70, in __init__
    self.import_nodes(path=abs_path_from_package_dir('main/nodes/built_in/'))
  File "/usr/local/lib/python3.11/site-packages/ryven/gui/main_window.py", line 340, in import_nodes
    self.session.register_nodes(nodes)
  File "/usr/local/lib/python3.11/site-packages/ryvencore/Session.py", line 39, in register_nodes
    self.register_node(n)
  File "/usr/local/lib/python3.11/site-packages/ryvencore/Session.py", line 46, in register_node
    node_class.build_identifier()
  File "/usr/local/lib/python3.11/site-packages/ryvencore/Node.py", line 66, in build_identifier
    cls.identifier = prefix + cls.identifier
                     ~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by leon-thomm** [comment]
PySide2 is not yet compatible with Python 3.11. Indeed Ryven's version requirements currently do not account for PySide2 restrictions. It should do so in future releases.

**Comment by leon-thomm** [comment]
closed in https://github.com/leon-thomm/Ryven/releases/tag/v3.5.0

you can now use Python 3.11 with PySide6<6.7 `pip install 'pyside6<6.7'`
