### ISSUE TITLE
How to install and use?

### ISSUE THREAD

**Issue by simkimsia** [leon-thomm/Ryven#26]
I am using macOS cataline 10.15.7

**Comment by leon-thomm** [comment]
Guys, come on, it's really not difficult. You need what is stated in the requirements, as always on GitHub, and then you literally run the file from the the folder [_as described on the website_](http://ryven.org/guides).
If you have trouble running it on macOS, please open an issue with a precise description of the problem.

**Comment by simkimsia** [comment]
Sorry it's not that obvious to me.

**Comment by AlexRMU** [comment]
Win64
Python 3.4.0 (v3.4.0:04f714765c13, Mar 16 2014, 19:25:23)

```
C:\Windows\System32>python D:\Desktop\Ryven-2.4.1\Ryven\Ryven.py
Traceback (most recent call last):
  File "D:\Desktop\Ryven-2.4.1\Ryven\Ryven.py", line 4, in <module>
    import custom_src.Console.MainConsole as MainConsole
  File "D:\Desktop\Ryven-2.4.1\Ryven\custom_src\Console\MainConsole.py", line 75
    context = {**old_context, **new_context}  # merge dicts
                ^
SyntaxError: invalid syntax
```

**Comment by leon-thomm** [comment]
Please update your Python version :)
In this case, the ** syntax was introduced in Python 3.5 I think.

**Comment by AlexRMU** [comment]
```
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen DPI.
   QT_SCALE_FACTOR to set the application global scale factor.
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
https://www.qt.io/pricing
$233?

**Comment by leon-thomm** [comment]
per month, yes......... no, of course not :D
You need PySide2 to run Ryven. You can use it freely for _uncommercial_ use. Did you install it? Which version do you have?

**Comment by leon-thomm** [comment]
For installing use `pip install pyside2`, for upgrading use `pip install pyside2 --upgrade`
In case you still see that error after upgrading: where exactly does it print that? And how did you start the app?

**Comment by AlexRMU** [comment]
PySide2 is already installed
Python\Launcher\py.exe or cmd -> Ryven.py and Ryven NodeManager.py

**Comment by AlexRMU** [comment]
There may be a problem in Windows?

**Comment by leon-thomm** [comment]
yes. hm, that doesn't sound like a normal python path, it should be something like `programs/Python38/python.exe`. Did you try just opening it with python from the file explorer?
and please tell me your pyside2 version (`pip freeze`)

**Comment by AlexRMU** [comment]
I reduced the path for the sake of brevity. Via explorer = via py.exe
```
PySide2==5.15.1
shiboken2==5.15.1
```

**Comment by leon-thomm** [comment]
yeah, but thing is I don't directly use the macros you the warning above shows. So the problem probably isn't inside Ryven

**Comment by AlexRMU** [comment]
1. `pip install pyqt5` 
2. copy `Python39\Lib\site-packages\PyQt5\Qt\plugins\platforms` to `Python39\` (i.e. `Python39\platforms`) (Python39 means python root folder like Python38 or Python 26)
3. Everything worked
but outputs to the console:
```
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen DPI.
   QT_SCALE_FACTOR to set the application global scale factor.
```

**Comment by AlexRMU** [comment]
Done

**Comment by leon-thomm** [comment]
I don't really see... In any case, I would _not_ recommend running it like that, PySide2 and PyQt5 are different things. Might work, but bigger problems won't be avoidable probably

**Comment by AlexRMU** [comment]
[Is this normal?](https://i.ibb.co/Sx04Wb7/image.png)
Judging by the pictures and videos, this should be a big list

**Comment by AlexRMU** [comment]
> I don't really see why you do that... In any case, I wouldn't recommend running it like that, PySide2 and PyQt5 are not exactly the same and I would speculate, it's not a good idea to mix the configurations. Might work, though, idk

The program required qt - I installed qt

**Comment by leon-thomm** [comment]
> The program required qt - I installed qt
![grafik](https://user-images.githubusercontent.com/29960068/99195014-71e58b80-2783-11eb-8099-8fdc4b81de38.png)

**Comment by ValdemarQ** [comment]
How to run the software?

1. I open CMD
2. Cd to Ryven folder
3. run ryven.py
4. Visual editor opens the code editor with ryven.py code in it, instead of visual editor. 

Can you help?

**Comment by leon-thomm** [comment]
you need to start it with python, seems like you have set .py file extensions in your OS to open in an editor, instead of with Python.
if your python is set up correctly: `python Ryven.py`

**Comment by ValdemarQ** [comment]
> you need to start it with python, seems like you have set .py file extensions in your OS to open in an editor, instead of with Python.
> if your python is set up correctly: `python Ryven.py`

Understood, thank you!

**Comment by leon-thomm** [comment]
no worries :)

**Comment by Mecil9** [comment]
same,
in macos run ryven.py,it's notice, how to fix it!
You might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: cocoa, minimal, offscreen.

**Comment by ChitaJazz** [comment]
Hi!My system is mac OS Big Sur 11.0.1.It looks so cool,however,I can't make it run properly.
Traceback (most recent call last):
  File "/Users/songpingping/Documents/passwords/python file/Ryven-2.4.2/Ryven/Ryven.py", line 4, in <module>
    import custom_src.Console.MainConsole as MainConsole
  File "/Users/songpingping/Documents/passwords/python file/Ryven-2.4.2/Ryven/custom_src/Console/MainConsole.py", line 3, in <module>
    from PySide2.QtWidgets import QWidget, QLineEdit, QGridLayout, QPlainTextEdit, QLabel, QPushButton
ModuleNotFoundError: No module named 'PySide2'

**Comment by leon-thomm** [comment]
did you install the dependencies?

**Comment by temco** [comment]
such a problem was met when I ran `python Ryven/Ryven.py` in the root folder of this project.
```
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by iamjuush** [comment]
> such a problem was met when I ran `python Ryven/Ryven.py` in the root folder of this project.
> 
> ```
> qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> ```

Same problem here for me too. Running on macOS big sur 11.1

**Comment by davesgonechina** [comment]
Similar problem to above trying to run on Chrombook crostini:
```
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/davesgonechina/.pyenv/versions/3.7.3/bin/platforms" ...
Cannot load library /home/davesgonechina/.local/share/virtualenvs/Ryven-LMfEpAUt/lib/python3.7/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so: (libxcb-util.so.1: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/home/davesgonechina/.local/share/virtualenvs/Ryven-LMfEpAUt/lib/python3.7/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /home/davesgonechina/.local/share/virtualenvs/Ryven-LMfEpAUt/lib/python3.7/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so: (libxcb-util.so.1: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
Looks like maybe a symlink would help?

**Comment by naim5am** [comment]
> Similar problem to above trying to run on Chrombook crostini:
> 
> ```
> Got keys from plugin meta data ("xcb")
> QFactoryLoader::QFactoryLoader() checking directory path "/home/davesgonechina/.pyenv/versions/3.7.3/bin/platforms" ...
> Cannot load library /home/davesgonechina/.local/share/virtualenvs/Ryven-LMfEpAUt/lib/python3.7/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so: (libxcb-util.so.1: cannot open shared object file: No such file or directory)
> QLibraryPrivate::loadPlugin failed on "/home/davesgonechina/.local/share/virtualenvs/Ryven-LMfEpAUt/lib/python3.7/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /home/davesgonechina/.local/share/virtualenvs/Ryven-LMfEpAUt/lib/python3.7/site-packages/PySide2/Qt/plugins/platforms/libqxcb.so: (libxcb-util.so.1: cannot open shared object file: No such file or directory)"
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> ```
> 
> Running ldd on `libqxcb.so`, I see `libxcb-util.so.1 => not found`
> 
> This led me to this [known bug](https://bugreports.qt.io/browse/QTBUG-88688) for QT on Debian 10 where libxcb-util.so.0 exists but libxcb-util.so.1 does not
> 
> I tried symlinking `libxcb-util.so.1` to the existing `libxcb-util.so.0` but got `"Failed to extract plugin meta data from '/usr/lib/x86_64-linux-gnu/libxcb-util.so.0.0.0'" not a plugin`

On linux, I usually do this to in a new directory. This tells python to install requirements separately from your user's python environment. 
``sudo apt install virtualenv `
``virtualenv env`
source env/bin/activate
pip install -r requirements.txt
