### ISSUE TITLE
No module named 'ryvencore_qt'

### ISSUE THREAD

**Issue by ouryperd** [leon-thomm/Ryven#64]
On Windows 7 with Python 3.8.3. When following the instructions, the following occurs:

```
C:\leon-thomm-Ryven-b8ba1fb>pip install -r requirements.txt
Requirement already satisfied: Jinja2 in c:\python38\lib\site-packages (from -r requirements.txt (line 2)) (2.11.2)
Requirement already satisfied: Pygments in c:\python38\lib\site-packages (from -r requirements.txt (line 3)) (2.6.1)
Requirement already satisfied: MarkupSafe>=0.23 in c:\python38\lib\site-packages (from Jinja2->-r requirements.txt (line 2)) (1.1.1)
Collecting ryvencore-qt
  Downloading ryvencore_qt-0.0.0-py3-none-any.whl (1.2 kB)
Collecting PySide2
  Downloading PySide2-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-none-win_amd64.whl (136.3 MB)
     |████████████████████████████████| 136.3 MB 6.3 kB/s
Collecting shiboken2==5.15.2
  Downloading shiboken2-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-none-win_amd64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 6.4 MB/s
Installing collected packages: shiboken2, PySide2, ryvencore-qt
Successfully installed PySide2-5.15.2 ryvencore-qt-0.0.0 shiboken2-5.15.2
WARNING: You are using pip version 20.3.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\python38\python.exe -m pip install --upgrade pip' command.

C:\leon-thomm-Ryven-b8ba1fb>cd Ryven\src

C:\leon-thomm-Ryven-b8ba1fb\Ryven\src>Ryven.py
Traceback (most recent call last):
  File "C:\leon-thomm-Ryven-b8ba1fb\Ryven\src\Ryven.py", line 83, in <module>
    main()
  File "C:\leon-thomm-Ryven-b8ba1fb\Ryven\src\Ryven.py", line 79, in main
    start_ryven()
  File "C:\leon-thomm-Ryven-b8ba1fb\Ryven\src\Ryven.py", line 17, in start_ryven
    from MainConsole import init_main_console
  File "C:\leon-thomm-Ryven-b8ba1fb\Ryven\src\MainConsole.py", line 5, in <module>
    from code_editor.CodeEditorWidget import CodeEditorWidget
  File "C:\leon-thomm-Ryven-b8ba1fb\Ryven\src\code_editor\CodeEditorWidget.py", line 1, in <module>
    from qtpy.QtWidgets import QTextEdit, QShortcut
ModuleNotFoundError: No module named 'qtpy'

C:\leon-thomm-Ryven-b8ba1fb\Ryven\src>pip install qtpy
Collecting qtpy
  Downloading QtPy-1.9.0-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 916 kB/s
Installing collected packages: qtpy
Successfully installed qtpy-1.9.0
WARNING: You are using pip version 20.3.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\python38\python.exe -m pip install --upgrade pip' command.

C:\leon-thomm-Ryven-b8ba1fb\Ryven\src>python Ryven.py
Traceback (most recent call last):
  File "Ryven.py", line 83, in <module>
    main()
  File "Ryven.py", line 79, in main
    start_ryven()
  File "Ryven.py", line 19, in start_ryven
    from MainWindow import MainWindow
  File "C:\Python38\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\leon-thomm-Ryven-b8ba1fb\Ryven\src\MainWindow.py", line 9, in <module>
    from ScriptUI import ScriptUI
  File "C:\Python38\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\leon-thomm-Ryven-b8ba1fb\Ryven\src\ScriptUI.py", line 3, in <module>
    from ryvencore_qt import GUI
  File "C:\Python38\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'ryvencore_qt'

C:\leon-thomm-Ryven-b8ba1fb\Ryven\src>
```

**Comment by leon-thomm** [comment]
ryvencore-qt had a python version tag of 3.9+, which is why it did not download the latest version but some dummy version (it should be `ryvencore_qt-0.0.2.something`). However, that tag was wrong, there is just something in Ryven that does not work with versions below 3.9. I just corrected that and pushed a new ryvencore-qt release to pypi, and added a check for the feature in Ryven and pushed to the master branch, so please try again now.

**Comment by ouryperd** [comment]
It was fixed with:

```
C:\leon-thomm-Ryven-b8ba1fb\Ryven\src>pip install ryvencore-qt --upgrade
```

Ryven runs now.
