### ISSUE TITLE
Cannot create new node

### ISSUE THREAD

**Issue by sarabiaf** [leon-thomm/Ryven#81]
I right-click in the canvas, and I see the dropdown list of available nodes.  However, I cannot find a way to create a node.  I have tried, enter, right-click, left-click, etc.. and nothing...
I have downloaded the latest version of ryven today directly from github...

**Comment by leon-thomm** [comment]
Both, enter and left click should work. Is there anything else strangely not working? Any you pulled from master branch, right?

**Comment by sarabiaf** [comment]
Yes, from the master.  There is a permissions issue.  See log below:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ryvencore_qt-0.0.2.8-py3.8.egg/ryvencore_qt/src/FlowView.py", line 787, in add_node

item = NodeItem(node, params=(self, self.session.design, item_config))

  File "/usr/local/lib/python3.8/dist-packages/ryvencore_qt-0.0.2.8-py3.8.egg/ryvencore_qt/src/NodeItem.py", line 70, in __init__

self.widget = NodeItemWidget(self.node, self)  # QGraphicsWidget(self)

  File "/usr/local/lib/python3.8/dist-packages/ryvencore_qt-0.0.2.8-py3.8.egg/ryvencore_qt/src/NodeItemWidget.py", line 26, in __init__

self.collapse_button = NodeItem_CollapseButton(node, node_item) if node.style == 'normal' else None

  File "/usr/local/lib/python3.8/dist-packages/ryvencore_qt-0.0.2.8-py3.8.egg/ryvencore_qt/src/NodeItem_CollapseButton.py", line 21, in __init__

self.collapse_pixmap = change_svg_color(Location.PACKAGE_PATH+'/resources/node_collapse_icon.svg',

  File "/usr/local/lib/python3.8/dist-packages/ryvencore_qt-0.0.2.8-py3.8.egg/ryvencore_qt/src/tools.py", line 98, in change_svg_color

with open(filepath, 'w') as f:

PermissionError
:
[Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/ryvencore_qt-0.0.2.8-py3.8.egg/ryvencore_qt/resources/node_collapse_icon.svg'

**Comment by leon-thomm** [comment]
ah yes, ryvencore-qt tries to save a file in the package's installation directory, but it can probably be avoided, I will try to change that. Until then, if you run it with root privileges it should work fine. On which OS do you try to run it?

**Comment by sarabiaf** [comment]
I am running Ubuntu 18.  I changed read/write permissions of the ryvencore-qt  directory, and it works now.  Thank you for help!
